### ISSUE TITLE
Trabalho avaliado

### ISSUE THREAD

**Issue by lucasferreira** [gosttavo/abp-front-end#22]
Opa, @gosttavo @Santinoni15 e @VitorLidorio,

Parabéns pelo trabalho e obrigado pela entrega! Já fiz minha avaliação aqui ;)

O trabalho de vocês está com um ótimo design, e tem grande potencial de trabalho.

Fico até um pouco _chateado_ de ter que observar que faltou dar uma melhorada no conceito dos CRUDs e também na ideia de ter pelo menos 2 deles, penso que na parte de usuário com as devidas proporções eu consiga considerar como um CRUD.

No caso dos restaurantes, cidades e itens do cardápio, poderíamos ter ousado em outras áreas tipo uma área para cadastrar restaurantes ou editar os itens de um cardápio e etc.

Fora esses "detalhes" (que eu acho que vocês poderão finalizar semestre que vem na disciplina de back-end), penso que outras coisa foram bacanas, gostei muito do uso do Context e da exploração do localStorage.

No geral, parabéns novamente \o/

**Comment by neskovek** [comment]
Valeu o feedback! ;)
